CREATE TABLE counties (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  code INT,
  name VARCHAR(255),
  capital_city VARCHAR(255)
);
INSERT INTO counties
  (code,name,capital_city) 
VALUES 
  (1,'Mombasa','Mombasa (City)'),
  (2,'Kwale','Kwale'),
  (3,'Kilifi','Kilifi'),
  (4,'Tana River','Hola'),
  (5,'Lamu','Lamu'),
  (6,'Taita Taveta','Voi'),
  (7,'Garissa','Garissa'),
  (8,'wajir','Wajir'),
  (9,'Mandera','Mandera'),
  (10,'Marsabit','Marsabit'),
  (11,'Isiolo','Isiolo'),
  (12,'Meru','Meru'),
  (13,'Tharaka Nithi','Chuka'),
  (14,'Embu','Embu'),
  (15,'Kitui','Kitui'),
  (16,'Machakos','Machakos'),
  (17,'Makueni','Wote'),
  (18,'Nyandarua','Ol Kalou'),
  (19,'Nyeri','Nyeri'),
  (20,'Kirinyaga','Kerugoya/Kutus'),
  (21,'Muranga','Muranga'),
  (22,'Kiambu','Kiambu'),
  (23,'Turkana','Lodwar'),
  (24,'West Pokot','Kapenguria'),
  (25,'Samburu','Maralal'),
  (26,'Trans Nzoia','Kitale'),
  (27,'Uasin Gishu','Eldoret'),
  (28,'Elgeyo Marakwet','Iten'),
  (29,'Nandi','Kapsabet'),
  (30,'Baringo','Kabarnet'),
  (31,'Laikipia','Rumuruti'),
  (32,'Nakuru','Nakuru'),
  (33,'Narok','Narok'),
  (34,'Kajiado','Kajiado'),
  (35,'Kericho','Kericho'),
  (36,'Bomet','Bomet'),
  (37,'Kakamega','Kakamega'),
  (38,'Vihiga','Vihiga'),
  (39,'Bungoma','Bungoma'),
  (40,'Busia','Busia'),
  (41,'Siaya','Siaya'),
  (42,'Kisumu','Kisumu'),
  (43,'Homa Bay','Homa Bay'),
  (44,'Migori','Migori'),
  (45,'Kisii','Kisii'),
  (46,'Nyamira','Nyamira'),
  (47,'Nairobi','Nairobi (City)'),
  (48,'Diaspora','Diaspora'),
  (49,'Prisons','Prisons');